import Navigation from "../components/navigation";

export const metadata = {
    title: "Next.js",
    description: "Generated by me",
};

export default function Layout({ // Layouts are nesting each other
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Navigation />
                {children}
            </body>
        </html>
    );
}
